tasks:
- workunit:
    clients:
      client.0:
      - fs/upgrade/volume_client
    env:
      ACTION: create
- print: "**** fs/volume_client create"
- ceph-fuse:
    client.0:
      mount_path: /volumes/_nogroup/vol_isolated
      mountpoint: mnt.0
      auth_id: vol_data_isolated
    client.1:
      mount_path: /volumes/_nogroup/vol_default
      mountpoint: mnt.1
      auth_id: vol_default
- print: "**** ceph-fuse vol_isolated"
- workunit:
    clients:
      client.0:
      - fs/upgrade/volume_client
    env:
      ACTION: populate
    cleanup: false
- workunit:
    clients:
      client.1:
      - fs/upgrade/volume_client
    env:
      ACTION: populate
    cleanup: false
- print: "**** fs/volume_client populate"
